version: '3.3'
services:
  node:
    build: .
    ports:
      - "8100:8100"
    expose:
      - "8100"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASES: userDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - "3306"
