name: Deploy-dev
'on':
  push:
    branches:
      - feature
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: prepare the docker-compose run
        run: |
          ls -l

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: dockerUserID/234-project-devops_shop:latest

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{secrets.HOST_USER_NAME}}
          key: ${{secrets.HOST_SSH_PRIVATE_KEY}}
          port: 22
          source: "docker-compose-dev.yml"
          target: "/home/ubuntu/se-project-234-2023-devops_shop2"

      - name: docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{secrets.HOST_USER_NAME}}
          key: ${{secrets.HOST_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/se-project-234-2023-devops_shop
            echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
            docker compose -f docker-compose-feature.yml down
            docker compose -f docker-compose-feature.yml pull
            docker compose -f docker-compose-feature.yml up -d
            rm -rf /home/ubuntu/se-project-234-2023-devops_shop2
